server:
  error:
    include-stacktrace: always
spring:
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/ORCLPDB1 # URL de conexao do Oracle
    username: LIBRARY # Nome de usuario do banco de dados Oracle
    password: LIBRARY # Senha do banco de dados Oracle
    driver-class-name: oracle.jdbc.driver.OracleDriver # Driver JDBC do Oracle
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
