CONNECT SYSTEM/oracle;

ALTER SESSION SET CONTAINER = ORCLPDB1;
CREATE TABLESPACE LIBRARY_TBS DATAFILE '/opt/oracle/oradata/ORCLCDB/ORCLPDB1/library01.dbf' SIZE 100M ONLINE;
CREATE TABLESPACE IDX_LIBRARY DATAFILE '/opt/oracle/oradata/ORCLCDB/ORCLPDB1/idx_library01.dbf' SIZE 100M;
CREATE USER LIBRARY IDENTIFIED BY LIBRARY DEFAULT TABLESPACE LIBRARY_TBS TEMPORARY TABLESPACE TEMP;
GRANT CREATE SESSION, ALTER SESSION, CREATE VIEW, CREATE TABLE, CREATE SEQUENCE TO LIBRARY;
GRANT CREATE SYNONYM, CREATE DATABASE LINK TO LIBRARY;
ALTER USER LIBRARY QUOTA UNLIMITED ON LIBRARY_TBS;
